import { StyleSheet } from 'react-native';
import { moderateScale } from 'react-native-size-matters';
import { widthPercentageToDP as wp, heightPercentageToDP as hp } from 'react-native-responsive-screen';

export default StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    alignItems: 'center',
    marginVertical: hp('2%'),
    paddingVertical: moderateScale(8),
  },
  headerText: {
    width: '70%',
    height: moderateScale(20),
    borderRadius: moderateScale(4),
  },
  cardContainer: {
    flex: 1,
    position: 'relative',
    paddingHorizontal: moderateScale(15),
  },
  card: {
    flex: 1,
    borderRadius: moderateScale(15),
    padding: moderateScale(15),
    marginBottom: moderateScale(10),
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.23,
    shadowRadius: 2.62,
  },
  dateText: {
    width: '50%',
    height: moderateScale(24),
    borderRadius: moderateScale(4),
    alignSelf: 'center',
    marginVertical: moderateScale(10),
  },
  dateRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: moderateScale(10),
  },
  hijriDate: {
    width: '40%',
    height: moderateScale(18),
    borderRadius: moderateScale(4),
  },
  locationText: {
    width: '30%',
    height: moderateScale(18),
    borderRadius: moderateScale(4),
    marginLeft: moderateScale(5),
  },
  prayerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: moderateScale(12),
    paddingVertical: moderateScale(10),
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
    width: wp('83%'),
    alignSelf: 'center',
  },
  prayerIcon: {
    width: moderateScale(24),
    height: moderateScale(24),
    borderRadius: moderateScale(12),
  },
  prayerLabel: {
    width: '30%',
    height: moderateScale(18),
    borderRadius: moderateScale(4),
    marginHorizontal: moderateScale(10),
  },
  prayerTime: {
    width: '20%',
    height: moderateScale(18),
    borderRadius: moderateScale(4),
    marginLeft: 'auto',
    marginRight: moderateScale(10),
  },
  notifIcon: {
    width: moderateScale(20),
    height: moderateScale(20),
    borderRadius: moderateScale(10),
  },
  countdownContainer: {
    marginTop: moderateScale(15),
    alignItems: 'center',
  },
  countdownLabel: {
    width: '40%',
    height: moderateScale(16),
    borderRadius: moderateScale(4),
    marginBottom: moderateScale(8),
  },
  countdownTime: {
    width: '30%',
    height: moderateScale(24),
    borderRadius: moderateScale(4),
    marginBottom: moderateScale(15),
  },
  progressBarContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '90%',
  },
  progressBarIcon: {
    width: moderateScale(20),
    height: moderateScale(20),
    borderRadius: moderateScale(10),
    marginRight: moderateScale(5),
  },
  progressBar: {
    flex: 1,
    height: moderateScale(6),
    borderRadius: moderateScale(3),
  },
  progressBarIconEnd: {
    width: moderateScale(24),
    height: moderateScale(24),
    borderRadius: moderateScale(12),
    marginLeft: moderateScale(5),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
  },
  navbar: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    height: hp('12%'),
    paddingBottom: moderateScale(10),
  },
  navItemContainer: {
    alignItems: 'center',
    width: '20%',
  },
  navIcon: {
    width: moderateScale(28),
    height: moderateScale(28),
    borderRadius: moderateScale(14),
    marginBottom: moderateScale(4),
  },
  navLabel: {
    width: moderateScale(40),
    height: moderateScale(12),
    borderRadius: moderateScale(4),
  },
  topButtons: {
    position: 'absolute',
    top: moderateScale(15),
    left: moderateScale(20),
    right: moderateScale(20),
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  todayIndicator: {
    width: moderateScale(40),
    height: moderateScale(40),
    borderRadius: moderateScale(20),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
  },
  quoteButton: {
    width: moderateScale(40),
    height: moderateScale(40),
    borderRadius: moderateScale(20),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
  },
});
